# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 01:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_date', models.DateField(default=datetime.date.today)),
                ('code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numbers', jsonfield.fields.JSONField()),
                ('winning', models.NullBooleanField()),
                ('code', models.CharField(max_length=100)),
                ('prize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='powerball_backend.Prize')),
            ],
        ),
    ]
